### ISSUE TITLE
building rxcpp on windows

### ISSUE THREAD

**Issue by WirthAware** [Reactive-Extensions/RxCpp#108]
IDE build also the makefile build ends up in errors:

Error [some error number] error C3203: 'value_type_t' : unspecialized alias template can't be used as a template argument for template parameter 'T', expected a real type [some files]

Seems the VC++ compiler not fully support these C++11 features? 
Any solution for that?

**Comment by kirkshoop** [comment]
I have compiled rxcpp with VS2013 and VS2015 preview. Which version was this?

**Comment by BenPope** [comment]
It would be a shame to back out my change, but alas, g++-4.9.2 ICEd when I tried to go further with alias templates, perhaps compilers just aren't ready.

**Comment by kirkshoop** [comment]
I will accept a pr that moves back to the long form. :)

**Comment by BenPope** [comment]
I'm not sure a full revert is necessary or desired, but a few more details such as the compiler version and a code example with the compiler error backtrace may help to pinpoint the problem.  A workaround for MSVC via an intermediate struct might be possible.

**Comment by kirkshoop** [comment]
Closing until there is more data

**Comment by WirthAware** [comment]
i did it with VS 2013 .. may be i missed some updates. thx so far

**Comment by BenPope** [comment]
"...the compiler error backtrace may help to pinpoint the problem..."
