### ISSUE TITLE
Can't create observable

### ISSUE THREAD

**Issue by antlafarge** [Reactive-Extensions/RxCpp#119]
Hello,  

I can't create an observable like this "cep" example :  
https://github.com/Reactive-Extensions/RxCpp/blob/bd97cedb5a11c0666c14efa9d5abb9769480a884/Rx/v2/examples/cep/main.cpp#L19  
  
    IntelliSense: no instance of function template "rxcpp::observable<void, void>::create" matches the argument list
        argument types are: (lambda []void (rxcpp::subscriber<int, rxcpp::observer<int, rxcpp::dynamic_observer<int>>> dest)->void) ...  

Is the example broken or did I do something wrong?

**Comment by kirkshoop** [comment]
Intellisense is separate from the complier. I have tried rxcpp with vs2013 and vs2015 on windows and they should compile the cep example.

**Comment by antlafarge** [comment]
Okay I confirm.
So the project is too complex for intellisense ! ^^
Thank you.

**Comment by antlafarge** [comment]
Hello I'm back ! I encounter another problem when I try to create the observable (at runtime). the subscriber seams to be invalid in the called lambda.

Here is a part of code :

	rx::observable<Packet*> Scene::onMessage(Route* route)
	{
		auto observable = rx::observable<>::create<Packet*>([this, route](rx::subscriber<Packet*> subscriber) {
			auto handler = new function<void(Packet*)>([this, &subscriber](Packet* p) {
				auto packet = new Packet(host(), p->stream, p->metadata());
				subscriber.on_next(packet); // Access violation reading location here !
			});

			subscriber.add([route, handler]() {
				// ...
			});
		});
		return observable.as_dynamic();
	}

the error:

Unhandled exception at 0x5A5066FF in Echo.exe: 0xC0000005: Access violation reading location 0x8B55FF8B.

What can be the issue?

**Comment by kirkshoop** [comment]
Briefly, I am traveling. 

The &subscriber must be subscriber. Without this the subscriber lifetime is over when the subscribe method exits.

**Comment by antlafarge** [comment]
Okay it works !
Thanks
