### ISSUE TITLE
Observer / observable as member of a class

### ISSUE THREAD

**Issue by antlafarge** [Reactive-Extensions/RxCpp#120]
Hello,

I created an observer by applying the onNext and onError functions.  
After I get an observer from the subscriber (by creating an observable on same data type).
This observers, get from 2 differents sources, but handling the same data type, seams to have different signatures.

How to align the signature of this 2 observers get from different sources, and copy to a member of a class? (No "auto" allowed here).

EDIT:
Similar problem with the observable.
I create it by setting to it a lambda. I need to copy this observable in a member of a class.
Here is the error displayed by vc++

    Error C2440: 'return' : cannot convert from 'rxcpp::observable<T,rxcpp::sources::detail::create<T,Scene::onMessage::<lambda_4e1311247554cfa7219cec4f9e2964dd>>>' to 'rxcpp::observable<int,rxcpp::dynamic_observable<T>>' ...

The signature I use is `rx::observable<int>`

**Comment by BenPope** [comment]
Chain .as_dynamic() on the end of what you're returning.

**Comment by kirkshoop** [comment]
Yes, as_dynamic is explicit because it introduces virtual functions to forget the static type. Both observer and observable have as_dynamic.

**Comment by antlafarge** [comment]
Okay great, thank you
