### ISSUE TITLE
interval(TimePoint when) ambiguity

### ISSUE THREAD

**Issue by ValeryKopylov** [Reactive-Extensions/RxCpp#123]
Actual implementation of ```interval(TimePoint when)``` waits for the specified time point and then starts emitting integers infinitely:

```cpp
    auto scheduler = rxcpp::identity_current_thread();
    auto start = scheduler.now();
    auto values = rxcpp::observable<>::interval(start, scheduler);
    auto s = values.
        map([&](int prime) { 
            return std::make_tuple(std::chrono::duration_cast<std::chrono::milliseconds>(scheduler.now() - start).count(), prime);
        });
    s.
        take(3).
        subscribe(
            rxcpp::util::apply_to(
                [](__int64 t, int v){printf("OnNext: %d. %ld ms after the first event\n", v, t);}),
            [](){printf("OnCompleted\n");});
```
```
OnNext: 1. 0 ms after the first event
OnNext: 2. 0 ms after the first event
OnNext: 3. 0 ms after the first event
OnCompleted
```

It happens because the default value of ```period``` is ```rxsc::scheduler::clock_type::duration::max()```, and that causes integer overflow on the next occurence time calculating: ```*target += period;```. So we schedule the next integer in deep past and emit it immediately.

Is this the intended behavior or an issue?

**Comment by ValeryKopylov** [comment]
P.S. On Rx.NET, there is ```interval(period)``` instead of ```interval(when)```. This choice looks more useful, probably we should switch our implementation to this.

**Comment by kirkshoop** [comment]
This is an issue. The max value for period is intended to be invalid. This would mean that on_next is called only once in this case and then on_completed is called. 

I think that we should support only passing the period, only passing the initial time and passing both. What do you think?

**Comment by ValeryKopylov** [comment]
Intervals with the period and with both initial&period look good and conform with interval interface on RxNET and RxJava. As for interval with the initial time, RxNET and RxJava has ```timer``` operator that does exactly the same: 
> The Timer operator creates an Observable that emits one particular item after a span of time that you specify.

So, if we implement interval with the initial time, it could be confusing for people who is migrating from .NET/Java. In addition, timer is well described on introtorx and reactivex. Thereby I propose to modify interval to accept either the period or initial&period and make a new operator ```timer(when, [scheduler])```.

**Comment by kirkshoop** [comment]
Yes, that is a good idea.

**Comment by kirkshoop** [comment]
timer added in cf345e3f5c82e26ea434e287fe4974412f7f69d8
