### ISSUE TITLE
Builderror on linux 64 bit gcc

### ISSUE THREAD

**Issue by dhaeb** [Reactive-Extensions/RxCpp#125]
I pasted this code in my terminal while being in the root of RxCpp:

```bash
mkdir projects/build
cd projects/build
cmake -G"Unix Makefiles" -DCMAKE_C_COMPILER=gcc -DCMAKE_CXX_COMPILER=g++ -DCMAKE_BUILD_TYPE=RelWithDebInfo -B. ../CMake
make```
I got the following output / error message: 

```
~/dvl/cpp/RxCpp/projects/build$ cmake -G"Unix Makefiles" -DCMAKE_C_COMPILER=gcc -DCMAKE_CXX_COMPILER=g++ -DCMAKE_BUILD_TYPE=RelWithDebInfo -B. ../CMake
-- The C compiler identification is GNU 4.9.2
-- The CXX compiler identification is GNU 4.9.2
-- Check for working C compiler: /usr/bin/gcc
-- Check for working C compiler: /usr/bin/gcc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/g++
-- Check for working CXX compiler: /usr/bin/g++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Looking for include file pthread.h
-- Looking for include file pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- CMAKE_CXX_COMPILER_ID: GNU
-- using gnu settings
-- RXCPP_DIR: /home/dhaeb/dvl/cpp/RxCpp
-- Found Doxygen: /usr/bin/doxygen (found version "1.8.6") 
-- Configuring done
-- Generating done
-- Build files have been written to: /home/dhaeb/dvl/cpp/RxCpp/projects/build
~/dvl/cpp/RxCpp/projects/build$ make
Scanning dependencies of target one_test
[  2%] Building CXX object CMakeFiles/one_test.dir/home/dhaeb/dvl/cpp/RxCpp/Rx/v2/test/test.cpp.o
/home/dhaeb/dvl/cpp/RxCpp/Rx/v2/test/test.cpp:11:21: fatal error: catch.hpp: No such file or directory
 #include "catch.hpp"
                     ^
compilation terminated.
make[2]: *** [CMakeFiles/one_test.dir/home/dhaeb/dvl/cpp/RxCpp/Rx/v2/test/test.cpp.o] Error 1
make[1]: *** [CMakeFiles/one_test.dir/all] Error 2
make: *** [all] Error 2
```
Where is the catch.hpp file? A ```find . -name "catch.hpp"``` couldn't find it ether...

**Comment by kirkshoop** [comment]
catch is a git submodule. the initial clone should use --recursive switch, or use 'git submodule update --init --recursive' in your current clone.

**Comment by dhaeb** [comment]
Thanks I don't saw any hint in the readme regarding any git submodules.
Maybe I missed something there - but if not, I suggest it would be great to
inform the users.

Kirk Shoop <notifications@github.com> schrieb am So., 10. Mai 2015 21:51:
