### ISSUE TITLE
connect/publish threading issue

### ISSUE THREAD

**Issue by jpattersonz** [Reactive-Extensions/RxCpp#127]
consider this:

	auto published_observable =
		rx::sources::range(1, 100)
		.filter([](int i)
		{
			std::this_thread::sleep_for(std::chrono::milliseconds(100));
			std::cout << i << std::endl;
			return true;
		})
		.subscribe_on(rx::observe_on_new_thread())
		.publish();

	auto subscription = published_observable.connect();
	std::this_thread::sleep_for(std::chrono::seconds(1));
	subscription.unsubscribe();
	std::cout << "unsubscribed" << std::endl;

I expect this to print 10ish numbers then "unsubscribed".  However it prints the entire range up to 100.  Am I missing something?  I looked around at the source for publish and connect but I couldn't figure out a solution to my problem.  I need to be able to unsubscribe the connect()ed subscription.

Thanks for your help,

Jeff

**Comment by kirkshoop** [comment]
There was a bug in subscribe_on where the worker lifetime ended before the unsubscribe could be propagated. 

I have merged a fix in #128

**Comment by jpattersonz** [comment]
Thanks for the quick fix!
