### ISSUE TITLE
Reducing of empty observable

### ISSUE THREAD

**Issue by ValeryKopylov** [Reactive-Extensions/RxCpp#136]
When ```Reduce```, ```Average```, ```First```, or ```Last``` operator is applied to an empty sequence, on Rx.NET and RxJava it causes OnError().

On RxCpp we have different behavior:
```reduce``` returns ```result_selector(seed)```
```average``` returns 0 (```T()``` to be correct)
```first``` calls ```abort()```
```last``` calls ```abort()```
I propose to call OnError() for all operators. @kirkshoop, please let me know your opinion.

**Comment by kirkshoop** [comment]
Okay, let's follow the on-error pattern

**Comment by kirkshoop** [comment]
I am rethinking my stance on this.

I accept that sum, average, first and last should error for empty sources.

I do not agree that count should error for empty sources. count should return 0.
I do not agree that reduce should throw for empty. It is passed a seed and the result selector is allowed to throw if the seed has not been accumulated. If result errors by default then count has to catch the error and return 0. I do not like exceptions or errors for expected conditions.

**Comment by kirkshoop** [comment]
If an exception will be thrown for empty sources it should be a new exception type. The new type should inherit from std::range_error or std::runtime_error

The name for the new exception could be rxcpp::empty_error

**Comment by ValeryKopylov** [comment]
As we discussed, if the source observable throws an exception, then ```blocking_observable``` should catch it, save to a stack variable, and rethrow when it is safe. 
If the ```ResultSelector``` of ```reduce``` operator from regular ```observable``` throws, should we catch the exception and emit it as ```on_error``` or do nothing and let client code catch it?

**Comment by kirkshoop** [comment]
An exception from resultselector must be caught and passed to onerror

**Comment by ValeryKopylov** [comment]
> as_blocking().subscribe() now throws when on_error terminates the stream.

What is the desired behavior of blocking count, sum, and average:
1. Catch the exception and return the accumulated result.
2. The same but return 0.
3. Do nothing with the exception.

**Comment by kirkshoop** [comment]
3. Do nothing with the exception.

If the exception was from the source, then the caller should receive the thrown exception.
If the exception is `empty_error` then the caller should receive the thrown exception.

Once the `catch_error` operator exists the user can control this in the expression before `subscribe`.

**Comment by ValeryKopylov** [comment]
Ok, thanks!

One more question then. Is it really required to throw an exception for on_error in blocking_observable? Such behavior breaks examples like this:

```
SCENARIO("threaded error sample"){
    printf("//! [threaded error sample]\n");
    auto values = rxcpp::observable<>::error<int>(std::runtime_error("Error from source"), rxcpp::observe_on_event_loop());
    values.
        as_blocking().
        subscribe(
            [](int v){printf("OnNext: %d\n", v);},
            [](std::exception_ptr ep){
                try {std::rethrow_exception(ep);}
                catch (const std::exception& ex) {
                    printf("OnError: %s\n", ex.what());
                }
            },
            [](){printf("OnCompleted\n");});
    printf("//! [threaded error sample]\n");
}
```

The changes make impossible to handle an error in on_error lambda of subscriber.

**Comment by kirkshoop** [comment]
Okay, I agree, that seems like a bad change in behavior.

desired `on_error` behavior
 1. The default if no `on_error` is supplied is to abort the process.
 2. A supplied `on_error` that does not throw will suppress the error.
 3. A supplied `on_error` that does throw will abort the process.

Currently `blocking_observable::subscribe` changes 2. so that the error is re-thrown.

Please add `blocking_observable::subscribe_with_rethrow` and use it in `blocking_observable::last` and `blocking_observable::first`. Then change `blocking_subscribe` so that it only stores the exception_ptr (in the `on_error` lambda) if called by `subscribe_with_rethrow`

**Comment by kirkshoop** [comment]
These changes have been pushed! Thanks!
