### ISSUE TITLE
Not all source code available in VS2012 solution?

### ISSUE THREAD

**Issue by daixtrose** [Reactive-Extensions/RxCpp#144]
Maybe I missed something, but AFAICS the header files are not included with the VS solution/project generated by CMake-3.2.2, are they? I can only access these via external dependencies.
I do not see any files from the ```Rx/v2/src/rxcpp``` directory included directly. Is this by purpose and can we add them to the solution? 

![image](https://cloud.githubusercontent.com/assets/5588692/8001295/ac95f9a4-0b64-11e5-9dd4-e6a4cf49f662.png)

**Comment by daixtrose** [comment]
Solution proposals

* https://github.com/cognitivewaves/CMake-VisualStudio-Example
* http://stackoverflow.com/questions/1167154/listing-header-files-in-visual-studio-c-project-generated-by-cmake
* http://stackoverflow.com/questions/29986353/adding-header-and-cpp-files-in-a-project-built-with-cmake

There is some discussion/tradeoff whether to (1) add the files automatically (using *.h) or (2) explicitly. From what I learned from Google the first option seems to have the drawback that CMake will not detect additional files and fails to recreate the solution and project files while option 2 means manual adoption of CMake file every time one adds a file to the system.

What do you think?

**Comment by kirkshoop** [comment]
My initial thought is to list them explicitly. We start there and change as needed.

**Comment by daixtrose** [comment]
I agree. Shall I give it a try or do you want to do it?

**Comment by kirkshoop** [comment]
Please give it a try, thanks!

**Comment by daixtrose** [comment]
Please assign this issue to me if possible. I am working on it.
