### ISSUE TITLE
What is the purpose of as_dynamic?

### ISSUE THREAD

**Issue by daixtrose** [Reactive-Extensions/RxCpp#145]
Do I get it right that the ```as_dynamic``` method is a workaround for a type deduction issue?

**Comment by BenPope** [comment]
It's type erasure.

observable<T, U> becomes observable<T>, so U, the next thing in the chain, is no longer relevant at compilation time.  It means you can put the observable<T> on an interface exposed in a header file, without every caller needing to see the implementation, U.

**Comment by daixtrose** [comment]
So it is an emulation of interfaces without using inheritance - right?

**Comment by BenPope** [comment]
It's type-erasure like std::function or std::shared_ptr deleter; the runtime polymorphism (inheritance and virtual function calls) are within the implementation of the returned object.

**Comment by daixtrose** [comment]
OK, then things are clear.
