### ISSUE TITLE
Implementation of catch operators

### ISSUE THREAD

**Issue by hasyimibhar** [Reactive-Extensions/RxCpp#158]
Are there any plans for implementing the [catch operators](http://reactivex.io/documentation/operators/catch.html)? I wanted to use `onErrorResumeNext`, but I realized it's not implemented yet for RxCpp. I'm using RxCpp to write a web api client for my application. Basically, I want to be able to do something like this:

```cpp
apiClient.fetchSomeResource(token)
   .on_error_resume_next([apiClient](std::exception_ptr e) {
      try {
         std::rethrow_exception(e);
      } catch (const UnauthorizedHttpException &e) {

         // When server returns 401, call authenticate() to get
         // a new token, and then recall the same api
         return apiClient.authenticate()
            .flat_map([](const AuthToken &token) {
               return apiClient.fetchSomeResource(token);
            }, [](const AuthToken &token, Resource resource) {
               return resource;
            });

      } catch (const std::exception &e) {
         std::rethrow_exception(e);
      }
   })
   .subscribe([](const Resource &resource) {
      //...
   });
```

**Comment by kirkshoop** [comment]
It should not be too difficult, but I have not gotten to that yet. 

contributions are welcome!

**Comment by kirkshoop** [comment]
well, no one volunteered, so I added on_error_resume_next
let me know if it works out.

**Comment by hasyimibhar** [comment]
Thank you! :+1:  I thought of implementing it myself, but after seeing the code base, I barely know where to begin. I don't have much experience with modern C++/C++11 codebase, since I write mostly "C with classes" C++.
