### ISSUE TITLE
unqualified `ptrdiff_t` & `size_t` use

### ISSUE THREAD

**Issue by MattPD** [Reactive-Extensions/RxCpp#164]
Is this intentional?

~~As of GCC 4.9 this is no longer supported (and it was never std. compliant) -- see "Header <cstddef> changes": https://gcc.gnu.org/gcc-4.9/porting_to.html~~
// Edit: this appears to refer to the header inclusion missing entirely.

Currently `#include <cstddef>` is used in two places:
- https://github.com/Reactive-Extensions/RxCpp/blob/dbf9f5254d9284b7175c176b4112bf5e9cc5109f/Rx/v2/src/rxcpp/rx-includes.hpp#L103
- https://github.com/Reactive-Extensions/RxCpp/blob/dbf9f5254d9284b7175c176b4112bf5e9cc5109f/Ix/CPP/src/cpplinq/linq.hpp#L147

A fix would be to either:
- fully qualify each use of `std::ptrdiff_t` and `std::size_t` (there aren't that many)
- replace `#include <cstddef>` with `#include <stddef.h>`

I presume the choice may very well be a matter of preference :-)

**Comment by kirkshoop** [comment]
I would prefer explicit use of std:: 

I think there was variation across compilers and std libraries that caused the explicit std:: to fail. Any solution would need to pass travisci and appveyor :)

**Comment by MattPD** [comment]
OK, let's see if this passes! :-)

**Comment by kirkshoop** [comment]
Looks great!
