### ISSUE TITLE
[Question] Does the return value of observable.subscribe()  disposable ? and How?

### ISSUE THREAD

**Issue by cult54321** [Reactive-Extensions/RxCpp#173]
Q1) Does  "rx::observable<>::create<T>(on_subscribe)" store return value of on_subscribe?
       I want "return value of on_subscribe == on_dispose"
Q2) How can I manually dispose subscription and register on_dispose ?
      ...
      auto subscription = observable.subscribe(handler_next,  handler_error, handler_completed);
      ??  subscription.dispose() ??
      ...

**Comment by kirkshoop** [comment]
Hi!

## Q1
This answer [stackoverflow](http://stackoverflow.com/a/29829606/599231) should help with Q1.

## Q2
Issue, #127, shows how to interrupt a published subscription similar to Q2. An [example](https://github.com/Reactive-Extensions/RxCpp/blob/master/Rx/v2/examples/stop/main.cpp) was added to demonstrate this case.

Without publish/connect there are two options:

##### returned subscription
```cpp
auto subscription = observable.subscribe(. . .);
subscription.unsubscribe();
```
##### provided subscription
In this case the same subscription (lifetime) can be shared across multiple subscribes.
```cpp
auto subscription = composite_subscription();
observable.subscribe(subscription, . . .);
subscription.unsubscribe();
```

**Comment by cult54321** [comment]
1. thanks for your kind anwer
2. I will review rxcpp source code and think aout that why you chose the way "register the callback on the subscriber object instead of returning it"

**Comment by kirkshoop** [comment]
RxJava does the same thing..
Both RxJava and Rxcpp pass the subscription into subscribe because Rx.Net was forced into several contortions to allow operators to check if the subscription was subscribed. This way allows a loop in create to check for is_subscribed and then exit.
