### ISSUE TITLE
Test suite fails on ARM GCC

### ISSUE THREAD

**Issue by ksinica** [Reactive-Extensions/RxCpp#175]
Hi, we are having some problems with RxCpp on ARM platform. RxCpp test suite is not passing, however on x86 and x86_64 platforms it runs just fine.

Target platform and toolchain details:
ARM Cortex-A8 VFPv3-D16
glibc 2.21
gcc-5.2.0
same errors were also generated on toolchain based on gcc-4.9.2 and uClibc (same hardware).

Test suite output:
http://hastebin.com/cugojuvexe.coffee

**Comment by kirkshoop** [comment]
thanks for the issue and fix!
