### ISSUE TITLE
Backpressure operators

### ISSUE THREAD

**Issue by fabioramponi** [Reactive-Extensions/RxCpp#177]
From what I saw, in RxCpp operators like `onBackpressureBuffer`, `onBackpressureDrop`, `onBackpressureLatest` described [here](http://reactivex.io/documentation/operators/backpressure.html) are not implemented.
Is there a plan to implement them in the near future?

**Comment by kirkshoop** [comment]
No, rxcpp does not implement backpressure. 

Contribution is welcome!

This would start with some discussion and prototyping. Rx.Net, RxJava and RxJs each have a different approach - rxcpp will have to pick one or invent another :)

**Comment by kirkshoop** [comment]
closed due to inactivity
