### ISSUE TITLE
Is Ix supported?

### ISSUE THREAD

**Issue by black78** [Reactive-Extensions/RxCpp#178]
I couldn't found a NuGet package with Ix.
I found more TODOs in linq.hpp:
// TODO: groupby(keyfn, eq)
// TODO: join...
// TODO: average
// TODO: concat
// TODO: default_if_empty
// TODO: distinct()
// TODO: distinct(cmp)
// TODO: except(second)
// TODO: except(second, eq)
// TODO: intersect(second)
// TODO: intersect(second, eq)
// TODO: order_by(sel)
// TODO: order_by(sel, less)
// TODO: order_by_descending(sel)
// TODO: order_by_descending(sel, less)
// TODO: sequence_equal(second)
// TODO: sequence_equal(second, eq)
// TODO: single / single_or_default
// TODO: skip_while(pred)
// TODO: sum
// TODO: take_while
// TODO: then_by / then_by_descending ?
// TODO: to_...
// TODO: union(second)
// TODO: union(eq)
// TODO: zip

Did you stop develop this very important project?
What is state of Ix part?

**Comment by kirkshoop** [comment]
open source projects are supported by those who use and contribute. By this definition Ix has little support at this time. 

I agree that algorithmic expressions over collections are very important. Personally, I believe that the [rangev3](https://github.com/ericniebler/range-v3) proposal to the C++ standard is the right place to investment in this functionality.

That said, contributions to Ix are welcome and will be merged.

**Comment by black78** [comment]
Thank you for your answer.
