### ISSUE TITLE
Make_event_loop::inner is empty

### ISSUE THREAD

**Issue by antlafarge** [Reactive-Extensions/RxCpp#185]
I encounter a bug when I create two workers using this code :  
`rxcpp::schedulers::make_event_loop().create_worker()`

Not everytime, but sometimes it crash because `inner` member is empty (in create_worker)
Do you know this issue?

I encounter this issue sometimes on a standalone app, and most of the time with the Unreal Engine 4 (when I call it several times).

**Comment by kirkshoop** [comment]
`create_worker()` does not appear to have an `inner`, but the `composite_subscription` parameter to `create_worker()` does have an `inner`. Is that `inner` empty? if so, how is that `composite_subscription` being passed? each `composite_subscription manages` one lifetime so each worker that needs a separate lifetime needs a separate subscription.
