### ISSUE TITLE
Create observable with disposable

### ISSUE THREAD

**Issue by kittinunf** [Reactive-Extensions/RxCpp#188]
In some implementation of Rx, when observable is manually created, api allow to optionally provide a manual disposable cleanup. 

Here is the example from RxJs
```Javascript
var o = Rx.Observable.create(function (observer) {
    observer.onNext(42);
    observer.onCompleted();
    return function () {
        console.log('disposed');
    };
});
```

I expect something along this line, but it doesn't seem to be supported.

``` C++
auto o = rxcpp::observable<>::create<int>([](rxcpp::subscriber<int> s) {
  s.on_next(42);
  s.on_complete();
  return []() { std::cout << "manual disposed" << std::endl; };
});
```

How can we achieve the same thing with RxCpp?

**Comment by kirkshoop** [comment]
this [answer on SO](http://stackoverflow.com/a/29829606/599231) should cover it.

Here it is applied to your question:
```cpp
auto o = rxcpp::observable<>::create<int>([](rxcpp::subscriber<int> s) {
  s.on_next(42);
  s.on_complete();
  s.add([]() { std::cout << "manual disposed" << std::endl; });
});
```
Of course `s.on_complete()` will unsubscribe before the `add`, so the `add` will immediately call the lambda.

**Comment by kittinunf** [comment]
Thank you so much! I think this should be somewhere in the tests as it is not quite obvious to find out!

**Comment by kirkshoop** [comment]
Yes, that makes sense. there is already some [docs for create](http://reactive-extensions.github.io/RxCpp/classrxcpp_1_1observable_3_01void_00_01void_01_4.html#a68356278fbcd12847cec55bcf96a0d00), but adding the unsubscribe callback is missing. (Not sure about the link, I haven't figured out how to make stable links in doxygen)

Anyone is welcome to contribute a PR. 

Thank you for the feedback!

**Comment by kittinunf** [comment]
Yup. I will close this issue as it has been answered. Thanks.
