### ISSUE TITLE
async_subject

### ISSUE THREAD

**Issue by schiebel** [Reactive-Extensions/RxCpp#193]
Here's my first pass at adding 'async_subject' and 'to_async(f)':

https://github.com/Reactive-Extensions/RxCpp/pull/192

Please let me know what you think...

**Comment by gchudnov** [comment]
Hi schiebel,

According to the [specs](http://reactivex.io/documentation/subject.html), AsyncSubject should emit the last value (and only the last value) emitted by the source Observable, and only after that source Observable completes.

I don't follow that logic in the provided code, sorry. Could you provide some details? 

Thank you!

**Comment by schiebel** [comment]
Thank you very much for the reference to the specs. I was working from the v1 rxcpp code. I'll work on another iteration!

**Comment by kirkshoop** [comment]
Thank you both for contributing here!

It is always difficult to review code that deals with threading. I always used extensive testing to stress the threading code paths. those tests are under the [perf] tag in the test binaries.

One thing that rxcpp has tried to do is to release locks before calling user provided functions. given the spec that @gchudnov referenced, I do not think that a lock needs to be held in async_subject.

**Comment by schiebel** [comment]
Thanks @kirkshoop ... yes, I had qualms about calling unknown code with a lock held. I'll also look at the testing examples.
