### ISSUE TITLE
distinct() not working with std::string

### ISSUE THREAD

**Issue by martinfinke** [Reactive-Extensions/RxCpp#204]
Please consider the following code:

```cpp
rxcpp::observable<std::string> obs = rxcpp::observable<>::just(std::string("Foo"));
obs.distinct(); // Error
```

The error is the `static_assert`:

> Function passed for lift() must have the signature subscriber<...>(subscriber<T, ...>)

Looking into it, `distinct()` calls `rxo::detail::distinct<std::string>` which is not enabled because `is_hashable<std::string>` seems to be false.

Now, `std::hash` [does have a specialization for `std::string`](http://en.cppreference.com/w/cpp/string/basic_string/hash), so why doesn't this work?

As a sidenote, why isn't it possible to write the following?

```cpp
rxcpp::observable<std::string> obs = rxcpp::observable<>::just("Foo");
```

**Comment by gchudnov** [comment]
Hi Martin,

`why doesn't this work?`
^^
it looks the implementation missed strings for `is_hashable`. Just made a PR. If it is ok and merged, the problem should be fixed.

**Comment by martinfinke** [comment]
Thanks for the very prompt reply and the PR!

**Comment by kirkshoop** [comment]
The fix has been merged. Thanks for the report and the quick fix!

**Comment by martinfinke** [comment]
Great, thanks!

**Comment by HiroshimaCC** [comment]
So does `is_hashable` (and then the `disctinct` operator) work with anything else than enum/integer/pointer/string? I'm getting the same compilation error with an observable returning a system_clock::time_point.

**Comment by kirkshoop** [comment]
Yes, is_hashable is a whitelist, so it only works with types that explicitly specialized filtered_hash.

 Additional types can be whitelisted in user code without requiring changes to rxcpp. But for std types like time_point<Clock> there should be a pr to add support in rxcpp

**Comment by kirkshoop** [comment]
Distinctuntilchanged works because it does not use hash, it uses ==

**Comment by HiroshimaCC** [comment]
Well apparently the C++ Standard doesn't provide a hash for the
system_clock::time_point type. So it can't be used as an unordered_set key.

2016-03-21 17:18 GMT-04:00 Kirk Shoop <notifications@github.com>:

> Distinctuntilchanged works because it does not use hash, it uses ==
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/Reactive-Extensions/RxCpp/issues/204#issuecomment-199490961>
>



-- 
Alexandre Bourlon
http://www.linkedin.com/in/abourlon

**Comment by gchudnov** [comment]
HiroshimaCC,
you can make `distinct()` compiling for a `time_point` if you create a custom specialization for std::hash and white-list it in RxCPP.

Here is an example:
```c++
#include <chrono>
#include <iostream>

using clock_type = std::chrono::high_resolution_clock;
using time_point_type = std::chrono::time_point<clock_type>;

namespace std {
    template<> struct hash<time_point_type> {
        typedef time_point_type argument_type;
        typedef std::size_t result_type;

        result_type operator()(const argument_type& s) const {
            using count_type = argument_type::duration::rep;
            return std::hash<count_type>{}(s.time_since_epoch().count());
        }
    };
}

namespace rxcpp {
    template <class T>
    struct filtered_hash<T, typename std::enable_if<std::is_convertible<T, time_point_type>::value>::type> : std::hash<T> {
    };
}

// using it:
    time_point_type now = clock_type::now();

    std::cout << std::hash<time_point_type>{}(now) << std::endl; // hash works

    auto values = rxcpp::observable<>::just(now).distinct(); // distinct works
    values
        .subscribe(
        [](const time_point_type& tp) {
            std::cout << "OnNext: " << tp.time_since_epoch().count() << std::endl;
        },
        []() {
            std::cout << "OnCompleted" << std::endl;
        });
```

Guess, I can try to generalize, groom it and issue a PR if you wish...
However, I'm not sure whether that kind of specialization should be in RxCPP or not. Are there any use-cases?

**Comment by HiroshimaCC** [comment]
Hi,

Thanks a lot for all your valuable answers. I actually did something along these lines (specializing `filtered_hash` with respect to the `std::hash` interface) and it worked well. I'm not a fan of specializing `hash` directly in the `std` namespace (even if it's allowed for case like this).

I'm just toying with Rx for now, so no, there is no "use-case" involved. And since `std::hash` doesn't support `time_point`, I don't think it should be supported out-of-the-box. But there could be an "extented" header supporting more common types maybe.

**Comment by kirkshoop** [comment]
Thanks for the report and the great responses!

since rxcpp is _a set of algorithms operating on values distributed in time_, the time types are so central that I would support adding add hash implementations for the `std::chrono::time_point<Clock>` and `std::chrono::duration<Clock>` types to rxcpp.
