### ISSUE TITLE
No std::hash for enums

### ISSUE THREAD

**Issue by martinfinke** [Reactive-Extensions/RxCpp#207]
Please consider this example:

```cpp
enum Movement {
    Walking,
    Jumping,
    Swimming
};
rxcpp::observable<Movement> movement;
```

In C++11 (Xcode 7.2.1, Apple LLVM 7.0.2), this gives the compiler error:
> rx-util.hpp:690:82: Implicit instantiation of undefined template 'std::__1::hash\<Movement\>'

`std::hash` is only specialized for enum types in C++14 and above:
> standard library provides specializations for all (scoped and unscoped) enumeration types **(since C++14)**
[Source](http://en.cppreference.com/w/cpp/utility/hash)

I can get the above code to compile by replacing the specialization of `filtered_hash` by this:

```cpp
template <class T> 
struct filtered_hash<T, typename std::enable_if<std::is_enum<T>::value>::type>
    : std::hash<typename std::underlying_type<T>::type> {};
```

But I don't know if that would work in all situations.

**Comment by kirkshoop** [comment]
Thanks for the report! 
I am trying your solution in #208

**Comment by kirkshoop** [comment]
fix is merged. Thanks!

**Comment by martinfinke** [comment]
Great!
