### ISSUE TITLE
add hash implementations for time_point and duration

### ISSUE THREAD

**Issue by kirkshoop** [Reactive-Extensions/RxCpp#212]
See #204 for motivating discussion.

since rxcpp is _a set of algorithms operating on values distributed in time_, the time types are so central that I would support adding the hash implementations (missing from std) for the `std::chrono::time_point<Clock>` and `std::chrono::duration<Clock>` types to rxcpp.

**Comment by alexandrebourlon** [comment]
I'd like to point out that it's illegal in C++ to specialize a `std` member for a non _user-defined type_, like `std::chrono::time_point` and `std::chrono::duration`.

SInce `is_hashable` is relying on `filtered_hash`, would it be ok to directly specialize the latter for those types instead?

**Comment by kirkshoop** [comment]
Yes, specializing `filtered_hash` for `time_point` and `duration` will satisfy the need in rxcpp.

**Comment by alexandrebourlon** [comment]
My humble contribution here #213

**Comment by kirkshoop** [comment]
I merged #213. very cool @alexandrebourlon, thank you!
