### ISSUE TITLE
zip(): different values from same source observable

### ISSUE THREAD

**Issue by martinfinke** [Reactive-Extensions/RxCpp#219]
Please consider the following code:

```cpp
subjects::behavior<int> b1(0);
subjects::behavior<double> b2(0.5);
auto o1 = b1.get_observable();
auto o2 = b2.get_observable();

o1.combine_latest(o2).zip(o1).subscribe([](const std::pair<std::pair<int, double>, int>& pair) {
    std::cout << "callback called with:" << std::endl;
    std::cout << "{{" << pair.first.first << ", " << pair.first.second << "}, " << pair.second << "}" << std::endl;
    assert(pair.first.first == pair.second);
});

std::cout << "b2 on_next()" << std::endl;
b2.get_subscriber().on_next(1.5);
b2.get_subscriber().on_next(2.5);
std::cout << "b1 on_next()" << std::endl;
b1.get_subscriber().on_next(1);

b1.get_subscriber().on_completed();
b2.get_subscriber().on_completed();
```

This is the output:

```
callback called with:
{{0, 0.5}, 0}
b2 on_next()
b1 on_next()
callback called with:
{{0, 1.5}, 1}
Assertion failed: (pair.first.first == pair.second), function operator(), file main.cpp, line 16.
```

Shouldn't `pair.first.first` and `pair.second` always be the same value in the callback, since both come from `o1`?
If I change `b1` to be a `subject`, the callback only gets called once (rightfully so), with the correct values.
If I take out the `assert` and call `b1`'s `on_next()` more times, the output is, to me, even more confusing:

```
callback called with:
{{0, 0.5}, 0}
b2 on_next()
b1 on_next()
callback called with:
{{0, 1.5}, 1}
callback called with:
{{0, 2.5}, 2}
callback called with:
{{1, 2.5}, 3}
callback called with:
{{2, 2.5}, 4}
callback called with:
{{3, 2.5}, 5}
```

**Comment by kirkshoop** [comment]
Hi!

This is by-design. :)

The behavior subject will send the current value to each subscribe and then send subsequent on_next

The zip and the combine_latest make separate subscriptions to o1. 

The zip queues the 0
The combine_latest stores the 0 and the .5
The zip produces the 0 .5 0
The combine_latest stores 1.5
The zip queues 0 1.5
The combine_latest stores 2.5
The zip queues 0 2.5
The zip produces 0 1.5 1
The combine_latest stores 1 
The zip queues 1 2.5

The combine latest produces the 0 multiple times with each of the o1 values. 

I find it difficult to find cases where zip is useful due to the coupling to the item count in each stream.

**Comment by martinfinke** [comment]
Oh, you're right…I misunderstood `zip`. Thanks for clearing that up. I want to get the most recent values from `o1.combine_latest(o2)`, but only when `o1` sends a value (not when `o2` sends values). In other words, `o1` should be a "trigger" for when the callback happens, but in the callback, I need the most recent values from `o1` and `o2`. I'm having a hard time figuring out how to do it though.

**Comment by kirkshoop** [comment]
Look up withlatestfrom. Rxcpp does not have it yet, but other experts implementations do. It should not be hard to implement, but I have not gotten around to it yet.

**Comment by martinfinke** [comment]
Ok, thanks! It would be great if it finds its way into rxcpp :)

**Comment by kirkshoop** [comment]
Yes, I also want that operator :)

However, it occurs to me that this one does not need the operator

```cpp
o1.map([](int){return o1.combine_latest(o2);}).subscribe([](const std::pair<std::pair<int, double>, int>& pair) {
    std::cout << "callback called with:" << std::endl;
    std::cout << "{{" << pair.first.first << ", " << pair.first.second << "}, " << pair.second << "}" << std::endl;
    assert(pair.first.first == pair.second);
});
```

does that work?

**Comment by kirkshoop** [comment]
Take a look at #220 ;)

**Comment by martinfinke** [comment]
Wow, that was quick! Great, I'll try it later today.
