### ISSUE TITLE
observable<>::just as default parameter value doesn't compile on VS2015

### ISSUE THREAD

**Issue by martinfinke** [Reactive-Extensions/RxCpp#224]
The following compiles fine on Clang, but not on VS2015:

```cpp
#include "rxcpp/rx.hpp"
#include <string>

class Foo {
public:
    Foo(const rxcpp::observable<std::string>& str = rxcpp::observable<>::just(std::string())) {}
};

int main (int argc, char* argv[]){
    Foo foo;
}
```

The compiler errors are a bit misleading, saying that a local variable cannot be used as a default parameter value.

**Comment by kirkshoop** [comment]
Hi!

Yes, it takes extra work to support each of the compilers.

In this case I would try 
```
Foo(const rxcpp::observable<std::string>& str = rxcpp::observable<>::just(std::string()).as_dynamic()) {}
```
or
```
Foo(const rxcpp::observable<std::string>& str = rxcpp::sources::just(std::string()).as_dynamic()) {}
```
to see if we can change the code-path in the compiler

**Comment by martinfinke** [comment]
Oh thanks, I didn't think of that. I worked around it by adding a `private` member like:
```cpp
static const rxcpp::observable<std::string> JustEmptyString;
```
and initializing that to `rxcpp::observable<>::just(std::string())`. As far as I understand it, the initialization also performs the type forgetting, but I like your solution better.
