### ISSUE TITLE
subscription lifetime  possible memory leak?

### ISSUE THREAD

**Issue by hoffis** [Reactive-Extensions/RxCpp#228]
```c++
struct lifetime{ ~lifetime(){std::cout << "end of life" << std::endl;}};
rxcpp::subjects::subject<int> s;
{
    s.get_observable().take(1).subscribe([lf = std::make_shared<lifetime>()](int i){});
}

s.get_subscriber().on_next(1);
s.get_subscriber().on_next(2);
```
In the snippet above lifetime destructor was never called. How can I force rx to remove lambda passed to subscribe? Is it correct behaviour or bug in rx?

**Comment by kirkshoop** [comment]
Hi!

When using a subject, the lifetime of the subscriptions to the subject are controlled by the `subscriber` returned from `get_subscriber` add
`s.get_subscriber().on_completed();`
or
`s.get_subscriber().on_error(...);`
or
`s.get_subscriber().unsubscribe();`

and all the subscriptions will complete.

**Comment by hoffis** [comment]
Hi! 
thank you for your reply.

In this simple case it is possible but in my application subject  is an event bus to which many clients are subscribed.  Is there any way to unsubscribe only this one subscription in order to release "lifetime" object?

Here is simplified example of what i would like to achive
```cpp
        struct EventBus
        {
            rxcpp::subjects::subject<std::string> s;

            void run_one()
            {
                //receive some events from socket
                //and pass them to s;
                s.get_subscriber().on_next("event");
            }

            rxcpp::observable<std::string> onEvent()
            {
                return s.get_observable();
            }

            rxcpp::observable<int> sendMsg(std::string msg){
                return rxcpp::observable<>::create<int>([msg](rxcpp::subscriber<int> s){
                    //async send msg to socket
                    //then when completed send status back
                    s.on_next(1);
                    s.on_completed();
                });
            }
        };

        struct Service
        {
            EventBus& bus;

            auto userRequest(std::string msg)
            {
                return bus.sendMsg("test")
                .concat_map([&bus = this->bus](int status)
                {
                    return bus.onEvent()
                        .filter([](std::string event){
                                //if event is response to 'test' take it
                                return true;
                        })
                        .take(1);
                },
                [](int, std::string event){
                    return event;
                });
            }
        };
```

There will be many pending requests at the same time so I can't call:
``s.get_subscriber().unsubscribe();``

after each userRequest there will be new subscription to:
`` bus.onEvent()`` which will cause memory leak.

**Comment by kirkshoop** [comment]
Well, stopping a particular 'subscribe' is done with operators like 'take' or by passing a 'subscription' to 'subscribe' and then call 'unsubscribe' later.

**Comment by kirkshoop** [comment]
The stop example shows some of this. 

https://github.com/Reactive-Extensions/RxCpp/blob/master/Rx/v2/examples/stop/main.cpp

**Comment by kirkshoop** [comment]
> after each userRequest there will be new subscription to:
bus.onEvent() which will cause memory leak.

specifically, the take operator here:
'''
                    return bus.onEvent()
                        .filter([](std::string event){
                                //if event is response to 'test' take it
                                return true;
                        })
                        .take(1);
'''

will unsubscribe after the first event that matches the filter predicate. if no matching event ever arrives, then this subscription will keep waiting. If there is a chance that a matching event will never arrive you have to have something (timeout, cancelation) to signal that the matching event is no longer interesting and the subscription watching for it should end.

**Comment by kirkshoop** [comment]
Please feel free to continue when you have more questions..

**Comment by hoffis** [comment]
Thank you for your help. 
take operator works as expected and there are no memory leaks. My concerns was that in my first example all lambdas passed to subscribe will be freed at ``s.get_subscriber().unsubscribe();``, but in modified example:
```cpp
struct lifetime{ ~lifetime(){std::cout << "end of life" << std::endl;}};
rxcpp::subjects::subject<int> s;
for(int i = 0; i  < 10; ++i)
{
    s.get_observable().take(1).subscribe([lf = std::make_shared<lifetime>()](int i){});
    s.get_subscriber().on_next(1);
}
s.get_subscriber().unsubscribe();
```
lambdas were freed successively after each loop iteration, and only last lambda stays until ``unsubscribe();``

**Comment by kirkshoop** [comment]
Glad to help!
