### ISSUE TITLE
Memory leak with flat_map/concat_map for streaming data

### ISSUE THREAD

**Issue by sthekepat** [Reactive-Extensions/RxCpp#233]
Hey Guys,
I'm a newbie to RxCpp and here is my simple program:
`range(0) |
        window(20) |
        concat_map([](observable<int> w) {
            return w |
                   reduce(
                           vector<int>(),
                           [](vector<int> &v, int b) {
                               v.push_back(b);
                               return move(v);
                           }) ;
        }) |
        subscribe<vector<int>>([](vector<int> ) {
        });
`
This simulates say, streaming quotes (continuous data) from a publisher.
There seems to be a lot of memory leak when using *_map in the above.
I do see, I am not calling on_complete as an unbounded range, but shouldn't
the individual windows of size  20 be cleaned up when they are done emitting?
Thanks for the reply,
sthekepat

**Comment by kirkshoop** [comment]
Hi, thanks for the report!

I tried the following on my mac:

To verify that the window is being closed I added a tap and a finally.

```
    interval(milliseconds(50)) | window(20) | concat_map([](observable<long> w) { 
        return w | 
            reduce( vector<long>(), [](vector<long> &v, long b) { 
                v.push_back(b); 
                return move(v); 
            }) |
            tap([](const vector<long>&){},[](){
                printf("window complete - ");
            }) |
            finally([](){
                printf("window final\n");
            }) ; 
        }) | subscribe<vector<long>>([](vector<long> ) { }); 
```

The output verified that the windows are being closed

```
window complete - window final
window complete - window final
window complete - window final
window complete - window final
window complete - window final
Killed: 9
```

I also attached Xcode and used the memory window to verify that there was no leak. Then I moved back to the original code.

```
    range(long(0)) | window(20) | 
    concat_map([](observable<long> w) { 
        return w | 
            reduce( vector<long>(), [](vector<long> &v, long b) { 
                v.push_back(b); 
                return move(v); 
            }) ; 
        }) | subscribe<vector<long>>([](vector<long> ) { }); 
```

I attached Xcode and used the memory window to verify that there was no leak. 

Perhaps you are using a different platform or compiler?
How did you measure the leak?

**Comment by sthekepat** [comment]
Windows 10.
gcc 5.3.0 in Cygwin 2.5.1
the simplest way to look at the memory creep is to look at the windows Task manager & reverse sort on 
memory, you will see the process come to the top very fast.
I tried the same program again to make sure.
Haven't use Valgrind or similar yet.

**Comment by kirkshoop** [comment]
I have not tried gcc on windows before. I will give that a try. Let me know if you find anything more. 

Thanks!

**Comment by kirkshoop** [comment]
I tried vc2015 on windows first and there was no leak.

I then tried cygwin and gcc. The leak is there. This appears to be a bug in cygwin, there is also a slight possibility that this is a bug in the gcc std library.

If anyone wishes to debug further into cygwin or gcc, please update this issue.

Thanks!

**Comment by sthekepat** [comment]
I will try it Linux with the same version of std lib and let you know.
Thanks.

**Comment by sthekepat** [comment]
I tried Valgrind & the basic memory monitor. No leaks detected in Linux, gcc 5.3.0.
Seems to be a windows std lib problem. Anybody else experience this on windows + gcc?

**Comment by kirkshoop** [comment]
I suggest trying msys + gcc on Windows. This would leave the Cygwin runtime as the source of the leak.

**Comment by kirkshoop** [comment]
please re-open if there is new information
