### ISSUE TITLE
IxCpp

### ISSUE THREAD

**Issue by srdjantot** [Reactive-Extensions/RxCpp#234]
Is there nuget package for IxCpp?

**Comment by sdcb** [comment]
What's the difference bewteen IxCpp & RxCpp?

**Comment by kirkshoop** [comment]
@sdcb 

IxCpp is similar to the [range-v3](https://github.com/ericniebler/range-v3) lib which is proposed for inclusion in the std. It is a set of composable algorithms over items distributed in space (vector, list, etc..) and uses a pair of iterators to describe the range.

RxCpp is a set of composable algorithms over items distributed in time (HTTP requests, User input [clicks, moves, keys], block IO, anything async) and uses observable/observer to describe the range of values in time.

@srdjantot 

IxCpp is no longer included in the RxCpp nuget. If a nuget autoconf was contributed to the repo to specify what the IxCpp nuget should contain, then I would merge that and use that to publish a separate nuget.
 
Thanks!

**Comment by kirkshoop** [comment]
closing, pending a PR..
