### ISSUE TITLE
Shouldn't zip complete when one of the observables completes?

### ISSUE THREAD

**Issue by helgoboss** [Reactive-Extensions/RxCpp#236]
I started to use the zip operator and was surprised that it doesn't complete if one of the input observables completes. The resulting observable can't emit anything anymore as soon as one of the input observables completes ... so shouldn't it complete as well?

Right now I have to use the take operator as workaround but that requires me to know the number of emitted items in advance, which is quite awkward. Thanks for any hints!

**Comment by kirkshoop** [comment]
Yes, this is a bug in zip. 

I do not have a fix for this bug yet. Pr's are welcome!

Until this is fixed, a workaround is to use take_until with each source.ignore_elements().concat(just(true)) merged together.

**Comment by kirkshoop** [comment]
Thank goodness for tests..

I went down the path of completing the output on the earliest complete.

but what should happen for this?

```
1-2-3|
----A-B-C-D-|
```

the current will do

```
----1A-2B-3C---|
```

naive early complete will do

```
----1A|
```

However, I think that what would be expected is

```
----1A-2B-3C|
```

and this is complicated..

still looking, thanks for the report!

**Comment by helgoboss** [comment]
Amazing. Thanks for fixing this so quickly!
