### ISSUE TITLE
Uninitialized memory in schedulable_queue

### ISSUE THREAD

**Issue by VorpalBlade** [Reactive-Extensions/RxCpp#245]
While debugging a program using rxcpp with valgrind I ran into a lot of uninitialized memory reports from schedulable_queue in rx-scheduler.hpp. Some further analysis revealed that the cause was "int64_t ordinal;" in that class which is never initialized to any value. However, the way it is used is still safe (possibly with the exception of it starting out at a really large value, as the value is signed, and signed integer overflow is undefined as far as I remember).

Still I would suggest initialising the variable to a value to reduce the amount of false positives reported when using analysis tools such as valgrind.

**Comment by kirkshoop** [comment]
I agree on all points. This is a very helpful contribution, thank you!
