### ISSUE TITLE
Visual Studio 2015 not supported?

### ISSUE THREAD

**Issue by frankinshtein** [Reactive-Extensions/RxCpp#246]
build log
https://dl.dropboxusercontent.com/u/12679384/web/rxcpp.txt
A lot of errors:
69>------ Skipped Build: Project: ALL_BUILD, Configuration: Debug Win32 ------
69>Project not selected to build for this solution configuration 
========== Build: 2 succeeded, 65 failed, 0 up-to-date, 2 skipped ==========

**Comment by kirkshoop** [comment]
Thank you for bringing this to my attention!

vs2015 is supported, but I probably have not tested against update #3.

What update are you using?

**Comment by frankinshtein** [comment]
latest VS Update3
rxcpp from master

**Comment by kirkshoop** [comment]
painful to track down, but working again now. Thanks!

**Comment by frankinshtein** [comment]
thanks!
