### ISSUE TITLE
add make install target

### ISSUE THREAD

**Issue by maiermic** [Reactive-Extensions/RxCpp#255]
I tried to call `make install` after I built the project and got surprised:

    make: *** No rule to make target 'install'.  Stop.

Please configure cmake to be able to install RxCpp library.

**Comment by kirkshoop** [comment]
Hi, thanks for the report.
What should make install do for a header only library?
I have expected that dependent projects would make rxcpp a hit sub module and add an include path.

**Comment by maiermic** [comment]
I'd like to run `cmake` with `-DCMAKE_INSTALL_PREFIX=/my/dir`. `make install` should create `lib/libRxCpp.so` and an `include` directory with all headers in `/my/dir`. In another cmake project I should be able to 

```
find_package(RxCpp REQUIRED)
include_directories(${RxCpp_INCLUDE_DIRS})
target_link_libraries(${PROJECT_NAME} ${RxCpp_LIBRARIES})
```

**Comment by kirkshoop** [comment]
Try it out and let me know if it needs more work!

**Comment by maiermic** [comment]
Thanks, works fine for me :+1:

**Comment by kirkshoop** [comment]
Great! thanks for the report!
