### ISSUE TITLE
Interactive Sum

### ISSUE THREAD

**Issue by xunilrj** [Reactive-Extensions/RxCpp#268]
I have forked the project and implemented the SUM method (for the interactive) because there is a TODO on the linq.hpp (https://github.com/Reactive-Extensions/RxCpp/blob/master/Ix/CPP/src/cpplinq/linq.hpp#L474)

One can see my implementation at:
https://github.com/xunilrj/RxCpp/blob/feature/sum/Ix/CPP/src/cpplinq/linq.hpp#L474

If this implementation is of interest, I can improve it (any suggestions?) and make a PR.

**Comment by kirkshoop** [comment]
looks good to me!

Please do submit as a PR. Just make sure to restore all the tests so that the new tests for sum are added to the original tests instead of replacing them.

Thanks!
