### ISSUE TITLE
Combining observables

### ISSUE THREAD

**Issue by marcobusemann** [Reactive-Extensions/RxCpp#270]
Currently i am trying to solve the following problem using RxCpp.

1. Assume we have an observable serving objects of A
2. For each served object trigger a task that returns an observable serving a single object of B and then completes.
3. Combine A and B and provide an observable that emits the result.

I am trying to figure out how to solve this the most elegant way. My first thought was to do it like this:

1. Use observable::create and pass a subscription (x)
2. Subscribe to observable<A>
3. For each A trigger the task and subscribe to observable<B>
4. Combine A and B and call x.onNext((A, B))

It feels like there should be a much simpler solution.
Does someone has a suggestions?

**Comment by BenPope** [comment]
My understanding of your problem is this:
```
observable<A>()
.concat_map([](A a) {
   return Task<B>()
   .map([a](B b) {
      return std::make_pair(a,b);
   });
});
```
Is that close?

**Comment by kirkshoop** [comment]
Hi @marcobusemann, 

Thanks for asking!

@BenPope has a great solution. 
Another resource is the code on this [slide](https://kirkshoop.github.io/cppcon2016/#15) - part of this [talk](https://www.youtube.com/watch?v=FcQURwM806o). 

The code can be reduced to the following, which is similar to what @BenPope posted.

```cpp
from("https://aka.ms/rxcppreadme", "https://aka.ms/rxcppreadme") | // A
flat_map([](string a) { // flat_map will do http requests at the same time, concat_map will not
  return httpGet(a) | // B
    map([a](response_t b) {
      return make_tuple(a, b);
    });
}) |
subscribe([](tuple<string, request_t>){
// code using a & b
});
```

**Comment by marcobusemann** [comment]
Wow, thanks to both of you. That put me in the right direction and both solutions work like a charm.
