### ISSUE TITLE
`window_with_time_or_count` doesn't seem to cap by count

### ISSUE THREAD

**Issue by d-led** [Reactive-Extensions/RxCpp#277]
Hi!

Am I wrong in assuming that in window with time or count the first window cap wins? I'd expect the windows to be capped at 100k, but they're clearly limited via the time. Or, maybe a scheduler is missing? 

In the quick [tryout of the `window_with_time_or_count` operator](https://github.com/d-led/rxcpp_operators/commit/27f4a7a3f3243a77a645e9938cd0aa6df90f0ed2) I'd expect the windows to be capped at 100k:

```cpp
#include <rx.hpp>
#include <chrono>
#include <string>
#include <memory>
#include <fmt/ostream.h>

int main() {
    int counter = 0, count = 0;
    auto values = rxcpp::observable<>::range(1, 1000000)
        .window_with_time_or_count(std::chrono::seconds(1), 100000);
    values.
        subscribe(
            [&counter, &count](rxcpp::observable<int> window) {
        int id = counter++;
        printf("[window %d] Create window\n", id);
        window.count()
            .subscribe([](int c) {printf("Count in window: %d\n", c); });
        //...
        window.subscribe(
            [id, &count](int v) {count++;},
            [id, &count]() {printf("[window %d] OnCompleted: %d\n", id, count); });
    });
}
```

output:

```
[window 0] Create window
Count in window: 170306
Len: 910731 (123456789101112131415161718192021222324252...)
[window 0] OnCompleted: 170306
[window 1] Create window
Count in window: 172957
Len: 1037742 (170307170308170309170310170311170312170313...)
[window 1] OnCompleted: 343263
[window 2] Create window
Count in window: 171106
Len: 1026636 (343264343265343266343267343268343269343270...)
[window 2] OnCompleted: 514369
[window 3] Create window
Count in window: 173769
Len: 1042614 (514370514371514372514373514374514375514376...)
[window 3] OnCompleted: 688138
[window 4] Create window
Count in window: 175673
Len: 1054038 (688139688140688141688142688143688144688145...)
[window 4] OnCompleted: 863811
[window 5] Create window
Count in window: 136189
Len: 817135 (863812863813863814863815863816863817863818...)
[window 5] OnCompleted: 1000000
```

**Comment by kirkshoop** [comment]
good catch! there is a bug in that operator.

the `releasewindow()` result, when the count is reached, is not being scheduled.

I will get a fix out soon.

**Comment by d-led** [comment]
superb! will wait for a nuget update :)

**Comment by kirkshoop** [comment]
I pushed through a github release v3.0.0 and a nuget release v3.0.1  (I made a mistake with v3.0.0)

Try it out and see if it works!

**Comment by d-led** [comment]
Will do. Thanks!

**Comment by d-led** [comment]
the window is now capped correctly, but getting a [crash at the end](https://github.com/Reactive-Extensions/RxCpp/issues/277) in Release (not in Debug).

**Comment by d-led** [comment]
the window is now capped correctly, but getting a [crash at the end](https://github.com/d-led/rxcpp_operators) if the window size is 0. Either the I'm using the operators wrong, or there's another bug, analyzing a bit

**Comment by kirkshoop** [comment]
Yes :)
I use `start_with` with the `reduce` operators that require at least one value.
