### ISSUE TITLE
Linkage issue using clang

### ISSUE THREAD

**Issue by jeromo** [Reactive-Extensions/RxCpp#297]
clang++ --version
clang version 3.9.0 (tags/RELEASE_390/final)
Target: x86_64-unknown-linux-gnu
Thread model: posix

Trying to build RxCpp
mkdir projects/build
cd projects/build
cmake -G"Unix Makefiles" -DCMAKE_C_COMPILER=gcc -DCMAKE_CXX_COMPILER=g++ -DCMAKE_BUILD_TYPE=RelWithDebInfo -B. ../CMake
make

The result shows that lib std can-t be resolverd
...
CMakeFiles/rxcpp_test_window_toggle.dir/operators/window_toggle.cpp.o:(.rodata._ZTVN5Catch13StreamBufImplINS_17OutputDebugWriterELm256EEE[_ZTVN5Catch13StreamBufImplINS_17OutputDebugWriterELm256EEE]+0x60): undefined reference to `std::__1::basic_streambuf<char, std::__1::char_traits<char> >::uflow()'
CMakeFiles/rxcpp_test_window_toggle.dir/operators/window_toggle.cpp.o:(.rodata._ZTVN5Catch13StreamBufImplINS_17OutputDebugWriterELm256EEE[_ZTVN5Catch13StreamBufImplINS_17OutputDebugWriterELm256EEE]+0x68): undefined reference to `std::__1::basic_streambuf<char, std::__1::char_traits<char> >::pbackfail(int)'
CMakeFiles/rxcpp_test_window_toggle.dir/operators/window_toggle.cpp.o:(.rodata._ZTVN5Catch13StreamBufImplINS_17OutputDebugWriterELm256EEE[_ZTVN5Catch13StreamBufImplINS_17OutputDebugWriterELm256EEE]+0x70): undefined reference to `std::__1::basic_streambuf<char, std::__1::char_traits<char> >::xsputn(char const*, long)'
clang-3.9: error: linker command failed with exit code 1 (use -v to see invocation)
test/CMakeFiles/rxcpp_test_window_toggle.dir/build.make:94: recipe for target 'test/rxcpp_test_window_toggle' failed

I've tried passing arguments -DCMAKE_CXX_FLAGS="-std=c++14 -stdlib=libstdc++"
with the same result

It works using  gcc instructions

**Comment by kirkshoop** [comment]
Thank you for the report!

I have not seen this before. I'll need to setup a repro.

**Comment by jeromo** [comment]
Hi
I'm going to try to reproduce the issue in an isolated environment in a
docker, and I'll send you.

2016-12-19 18:20 GMT+01:00 Kirk Shoop <notifications@github.com>:

**Comment by jeromo** [comment]
If you build the image of this Dockerfile, you'll get the issue reproduced

2016-12-20 7:34 GMT+01:00 Jesús Rojo <jrojomo@gmail.com>:

**Comment by gchudnov** [comment]
@jeromo 
please, specify libc++ like this:
```
-DCMAKE_CXX_FLAGS="-stdlib=libc++"
```
and you will be able to build the library.

**Comment by gchudnov** [comment]
btw, it looks RxCPP tests for clang are broken(?)

**Comment by jeromo** [comment]
All test generated and passed after using -DCMAKE_CXX_FLAGS="-stdlib=libc++" (and setting ENV LD_LIBRARY_PATH=$CLANG_HOME/lib:$LD_LIBRARY_PATH)
Thank you very much

**Comment by gchudnov** [comment]
You're welcome!

**Comment by kirkshoop** [comment]
@gchudnov I have not noticed broken tests on clang. What was the error?

**Comment by kirkshoop** [comment]
@gchudnov thanks for resolving this!

**Comment by gchudnov** [comment]
Looking at the test results, for example, [here](https://travis-ci.org/Reactive-Extensions/RxCpp/jobs/187313229):

It seems there is an error:
```
/Users/travis/.rvm/scripts/extras/bash_zsh_support/chpwd/function.sh: line 5: cd: build/test/: No such file or directory
```

And [the rest](https://travis-ci.org/Reactive-Extensions/RxCpp/builds/187313226) of the tests are for GCC, not Clang.

**Comment by kirkshoop** [comment]
@gchudnov ah,yes. 

The apple clang builds on Travis have been broken for a while. The make fails and then the tests fail. 

The second bug is that make and test failures in Travis do not mark the builds as failed. 

I have not spent the time to fix these bugs yet. In part because I test on OS X locally and also that the [linux clang](https://travis-ci.org/Reactive-Extensions/RxCpp/jobs/187313232) build on Travis is building and running the tests successfully.

**Comment by gchudnov** [comment]
@kirkshoop 
got it..

I might be wrong, but in the last link you provided I thought that is a GCC compiler (4.8.4), see the line [346](https://travis-ci.org/Reactive-Extensions/RxCpp/jobs/187313232#L346)
```
The C compiler identification is GNU 4.8.4
```

**Comment by kirkshoop** [comment]
Ouch. This even even worse than I thought!
