### ISSUE TITLE
build break at very beginning

### ISSUE THREAD

**Issue by huang-qiao** [Reactive-Extensions/RxCpp#342]
Hi,
I just followed the README but failed immediately.
here's the log. It looks like path error, compiler can't find a header "catch.hpp". Please help me fix it.

osx:build qiao$ cmake -G"Unix Makefiles" -DCMAKE_BUILD_TYPE=RelWithDebInfo -B. ../CMake
-- The C compiler identification is AppleClang 8.0.0.8000042
-- The CXX compiler identification is AppleClang 8.0.0.8000042
-- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc
-- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++
-- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- RXCPP_DIR: /Users/qiao/projects/RxCpp
-- RXCPP_DIR: /Users/qiao/projects/RxCpp
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - found
-- Found Threads: TRUE
-- CMAKE_CXX_COMPILER_ID: AppleClang
-- clang compiler version: 8.0.0.8000042
-- using clang settings
-- RXCPP_DIR: /Users/qiao/projects/RxCpp
-- Could NOT find Doxygen (missing:  DOXYGEN_EXECUTABLE)
-- RXCPP_DIR: /Users/qiao/projects/RxCpp
-- CMAKE_CXX_COMPILER_ID: AppleClang
-- clang compiler version: 8.0.0.8000042
-- using clang settings
-- RXCPP_DIR: /Users/qiao/projects/RxCpp
-- CMAKE_CXX_COMPILER_ID: AppleClang
-- clang compiler version: 8.0.0.8000042
-- using clang settings
-- RXCPP_DIR: /Users/qiao/projects/RxCpp
-- CMAKE_CXX_COMPILER_ID: AppleClang
-- clang compiler version: 8.0.0.8000042
-- using clang settings
-- RXCPP_DIR: /Users/qiao/projects/RxCpp
-- CMAKE_CXX_COMPILER_ID: AppleClang
-- clang compiler version: 8.0.0.8000042
-- using clang settings
-- RXCPP_DIR: /Users/qiao/projects/RxCpp
-- CMAKE_CXX_COMPILER_ID: AppleClang
-- clang compiler version: 8.0.0.8000042
-- using clang settings
-- RXCPP_DIR: /Users/qiao/projects/RxCpp
-- CMAKE_CXX_COMPILER_ID: AppleClang
-- clang compiler version: 8.0.0.8000042
-- using clang settings
-- Configuring done
-- Generating done
-- Build files have been written to: /Users/qiao/projects/RxCpp/projects/build
osx:build qiao$ make
Scanning dependencies of target RxCpp
[  0%] Linking CXX shared library libRxCpp.dylib
[  0%] Built target RxCpp
Scanning dependencies of target rxcpp_test_window_toggle
[  0%] Building CXX object test/CMakeFiles/rxcpp_test_window_toggle.dir/operators/window_toggle.cpp.o
In file included from /Users/qiao/projects/RxCpp/Rx/v2/test/operators/window_toggle.cpp:1:
/Users/qiao/projects/RxCpp/Rx/v2/test/operators/../test.h:22:10: fatal error: 'catch.hpp' file not found
#include "catch.hpp"
         ^
1 error generated.
make[2]: *** [test/CMakeFiles/rxcpp_test_window_toggle.dir/operators/window_toggle.cpp.o] Error 1
make[1]: *** [test/CMakeFiles/rxcpp_test_window_toggle.dir/all] Error 2
make: *** [all] Error 2

**Comment by kirkshoop** [comment]
The "Cloning rxcpp" section of the readme states that the the clone must be recursive to include the catch submodule. 

    git clone --recursive https://github.com/Reactive-Extensions/RxCpp.git

**Comment by huang-qiao** [comment]
Oh, I missed it! Thank you very much!
