### ISSUE TITLE
lift operator refactoring

### ISSUE THREAD

**Issue by gchudnov** [Reactive-Extensions/RxCpp#343]
@kirkshoop,

Just tried to [refactor](https://github.com/gchudnov/RxCpp/commit/d2463190703116b6bb6e5542f7bb34330cdd75cb) the `lift` operator, but it looks it doesn't fit exactly the new operator implementation pattern.

It would be great if you provided some implementation guidelines...

--
There is an explicit result type, e.g. ['int' in this test](https://github.com/gchudnov/RxCpp/commit/d2463190703116b6bb6e5542f7bb34330cdd75cb#diff-fe06b4f3e1014ed24c2b294e1eb192a1R177):

```
rxo::lift<int>(liftfilter([&invoked](int x) {...
           ^^^^
```
and I have to provide a [dummy variable](https://github.com/gchudnov/RxCpp/commit/d2463190703116b6bb6e5542f7bb34330cdd75cb#diff-3a14c614bdd8677f53f166b099fca77bR118) just for the sake of this type.
It works, but looks ugly... Not sure that is OK... 

Guess I can call `member_overload<lift_tag>::member` directly, but that _breaks_ the invocation pattern, where we call `observable_member(YYY_tag{},                *this, std::forward<AN>(an)...);` from the observable member function..

What do you think is the preferred solution?

**Comment by kirkshoop** [comment]
I left comments in the [commit](https://github.com/gchudnov/RxCpp/commit/d2463190703116b6bb6e5542f7bb34330cdd75cb)

general statement is that it is likely that only the doc location changes.
lift and subscribe are implemented in observable and called from the operator - this is the inverse of the rest of the operators which are implemented in the operator and call from the observable.

**Comment by gchudnov** [comment]
yeah, got it.
I'll change only the docs then..
