### ISSUE TITLE
is there anyway to avoid MSVC C4503 warning

### ISSUE THREAD

**Issue by sdcb** [Reactive-Extensions/RxCpp#350]
A very simple code will emit [C4503](https://msdn.microsoft.com/en-us/library/074af4b6.aspx?f=255&MSPPError=-2147217396):
```
int main()
{
	rxcpp::sources::range(1, 100)
		.filter([](int v) { return v % 2 == 0; })
		.map([](int v) { return v * v; })
		.tap([](int v) {
			std::cout << v << std::endl;
		}).subscribe([](int v) {}); 
}
```

> decorated name length exceeded, name was truncated

I wonder is there any way to avoid this annoying warning without disable it?

**Comment by sdcb** [comment]
I found that as_dynamic would convert to a short typeid, I wondering: 

1. is as_dynamic aimed to resolove this warning?
2. is there any runtime-cast in as_dynamic?

**Comment by kirkshoop** [comment]
I have always had to pragma suppress that warning :(

`as_dynamic` introduces type-forgetting. This inhibits the linker from making some optimizations, adds a heap alloc and adds virtual function call overhead at runtime for every call to on_next.

`as_dynamic` is useful for isolating a user from the implementation details.

```
observable<Click> pointerClicks();
```

`pointerClicks` can change the expression that produces the clicks and the user perceives no change in the type.

**Comment by sdcb** [comment]
Thanks, I get it.
