### ISSUE TITLE
Support for skip_while

### ISSUE THREAD

**Issue by martinfinke** [Reactive-Extensions/RxCpp#378]
Please add support for the `skip_while` operator ([this one](http://reactivex.io/documentation/operators/skipwhile.html)).

**Comment by kirkshoop** [comment]
This should be pretty easy to add since it will be similar to the existing `take_while()`

This would be a great place to start for someone wishing to contribute to rxcpp!

**Comment by kirkshoop** [comment]
closed - thanks to @nitrram !

**Comment by martinfinke** [comment]
@nitrram Thanks!
