### ISSUE TITLE
Disable tests and examples building.

### ISSUE THREAD

**Issue by geektoni** [Reactive-Extensions/RxCpp#382]
Hello,
I'm planning to use RxCpp inside a project (I'll include it by using CMake `ExternalProject_add`), but I'm interested only in having the header files and the library. Is there a way to disable tests and examples build process when compiling the library? Without tweaking the CMake files of course.

**Comment by anatoly-spb** [comment]
RxCpp is header only library so to include RxCpp into your project the following is enough:

     `INCLUDE_DIRECTORIES(${RXCPP_HOME}` $ENV{RXCPP_HOME}) 

where RXCPP_HOME is either CMake variable (passed to CMake as -DRXCPP_HOME=path) or environment variable.

**Comment by geektoni** [comment]
@anatoly-spb thank you for the quick answer! The CMake variable option is not exactly what I'm looking for since I want to automatize all the build process. That way the final user has only to run `cmake` and all the library needed will be downloaded automatically.

However, I've found a solution by setting to an empty string the `BUILD_COMMAND` of my `ExternalProject_Add` directive. This way RxCpp is just installed and none of its example/tests are built.

Thanks for the help!

**Comment by daixtrose** [comment]
Please reopen this issue: `FetchContent_Declare` is unnecessarily exposed to the unit tests, since `BUILD_COMMAND` is not an option available for it, so if you perform 

```cmake
FetchContent_Declare(
  rxcpp
  GIT_REPOSITORY https://github.com/ReactiveX/RxCpp
  GIT_TAG master
)

FetchContent_GetProperties(rxcpp)

if(NOT rxcpp_POPULATED)
  FetchContent_Populate(rxcpp)
  add_subdirectory(${rxcpp_SOURCE_DIR} ${rxcpp_BINARY_DIR} EXCLUDE_FROM_ALL)
endif()
```
`ctest` will report uncompiled unit tests as error. The only way to avoid this is manual inclusion of `Rx/v2/src/` via

```cmake
target_include_directories(
    ${CMAKE_PROJECT_NAME} PUBLIC
    ... 
    ${rxcpp_SOURCE_DIR}/Rx/v2/src/
    )  
```
Can you please mitigate this?

**Comment by xxseabxx** [comment]
I just tried it on Android and iOS with the snippet from @daixtrose.
Always see the whole bunch of rxcpp_test_.... in my project.
Any other solution?
