### ISSUE TITLE
rxcpp::observe_on_event_loop() leaks memory

### ISSUE THREAD

**Issue by nikobarli** [Reactive-Extensions/RxCpp#393]
The below codes:

```
int main() {
    auto threads = rxcpp::observe_on_event_loop();
    return 0;
}

```

triggers memory leak detection when run in Visual Studio debugger. Or, did I miss a cleanup sequence ?
I tried using v2.3.0 and v4.0.0

> Detected memory leaks!
> Dumping objects ->
> {673} normal block at 0x000001E955593170, 16 bytes long.
>  Data: <  XU            > A0 1E 58 55 E9 01 00 00 00 00 00 00 00 00 00 00 
> {672} normal block at 0x000001E955581E70, 96 bytes long.
>  Data: <  YU      YU    > A0 E8 59 55 E9 01 00 00 90 E8 59 55 E9 01 00 00 
> {671} normal block at 0x000001E95559E890, 56 bytes long.
>  Data: < Ah             > A8 41 68 82 F6 7F 00 00 01 00 00 00 02 00 00 00 
> {665} normal block at 0x000001E95559D290, 64 bytes long.
>  Data: < Dh       YU    > C8 44 68 82 F6 7F 00 00 10 C5 59 55 E9 01 00 00 
> {664} normal block at 0x000001E9555898A0, 48 bytes long.
>  Data: <P XU    P XU    > 50 9E 58 55 E9 01 00 00 50 9E 58 55 E9 01 00 00 
> {663} normal block at 0x000001E95559E810, 64 bytes long.
>  Data: < Hh             > 88 48 68 82 F6 7F 00 00 01 00 00 00 02 00 00 00 
> {662} normal block at 0x000001E9555931C0, 16 bytes long.
>  Data: <  YU            > E0 C5 59 55 E9 01 00 00 00 00 00 00 00 00 00 00 
>

**Comment by kirkshoop** [comment]
Thanks for the report~

#132 was fixed a while ago. There is a possibility that there is a leak that I missed. Another possibility is that this is more of a design issue where threads have not exited yet when the leak detection runs.

It may take me a while to look at this one. If you find more information please let us know.

**Comment by nikobarli** [comment]
I think the problem is inside the following lines inside rx-newthread.hpp. 

the shared_ptr 'state' (aliased to 'keepAlive') has circular shared reference to itself because it is captured by two lambdas and the lambdas are kept by its member ('worker' and 'lifetime'). I don't have any idea how to fix it though.

```cpp
new_worker(composite_subscription cs, thread_factory& tf)
            : state(std::make_shared<new_worker_state>(cs))
        {
            auto keepAlive = state;

            state->lifetime.add([keepAlive](){
                std::unique_lock<std::mutex> guard(keepAlive->lock);
                auto expired = std::move(keepAlive->q);
                if (!keepAlive->q.empty()) std::terminate();
                keepAlive->wake.notify_one();
            });

            state->worker = tf([keepAlive](){

                // take ownership
                queue_type::ensure(std::make_shared<new_worker>(keepAlive));
                // release ownership
                RXCPP_UNWIND_AUTO([]{
                    queue_type::destroy();
                });

                for(;;) {
                    std::unique_lock<std::mutex> guard(keepAlive->lock);
                    if (keepAlive->q.empty()) {
                        keepAlive->wake.wait(guard, [keepAlive](){
                            return !keepAlive->lifetime.is_subscribed() || !keepAlive->q.empty();
                        });
                    }
                    if (!keepAlive->lifetime.is_subscribed()) {
                        break;
                    }
                    auto& peek = keepAlive->q.top();
                    if (!peek.what.is_subscribed()) {
                        keepAlive->q.pop();
                        continue;
                    }
                    if (clock_type::now() < peek.when) {
                        keepAlive->wake.wait_until(guard, peek.when);
                        continue;
                    }
                    auto what = peek.what;
                    keepAlive->q.pop();
                    keepAlive->r.reset(keepAlive->q.empty());
                    guard.unlock();
                    what(keepAlive->r.get_recurse());
                }
            });
        }
```

**Comment by kirkshoop** [comment]
Yes, thank you for the investigation!

This one was a time sink. Most thread issues are - the reason that this library exists is to isolate user code from this kind of complexity.

This will shut down the new_thread workers when the last event_loop/event_loop worker instance is destructed.

This also makes unsubscribe on a new_thread join when possible.

> Note: When a worker is created it is required to unsubscribe the worker to clean it up.

Please try out #394 and see if it works for you.

Thanks!

**Comment by nikobarli** [comment]
I confirmed the memory leaks disappear after the fix. 

BTW, if I want to create my own scheduler, is there any guidance/docs/example to follow ? 
Currently I am thinking to create a task pool scheduler wrapping concurrency runtime thread pool. 

Thanks !

**Comment by kirkshoop** [comment]
yes, a thread pool scheduler would be great!

the new thread and current thread schedulers are the most tested. there is also an example using asio io_service. [github](https://github.com/pudae/example/blob/f71d550f8a6bacc881b6bb3e89e6528e1f6d54b2/rx_test/rxasio/io_service.hpp)

The requirements are:

- scheduler is a factory of workers
- each worker:
  - runs function @ time
  - only one function run at a time (strand)
  - multiple functions with the same T run FIFO

the recursion flag is used to optimize the case when a function reschedules itself. This can be set to always queue rescheduled functions.
