### ISSUE TITLE
item may be lost when using subscribe on

### ISSUE THREAD

**Issue by nikobarli** [Reactive-Extensions/RxCpp#396]
The following code will only print items 200 and 300 (the first item 100 is missing), due to the using of "subscribe_on". If I comment-in the "Sleep(1000)" to get more time before emitting item 100, then it will be OK. 

```cpp
        rxcpp::subjects::subject<int> subject;
        subject.get_observable()
            .subscribe_on(rxcpp::observe_on_new_thread())
            .subscribe([](auto && x) {
                std::cout << std::setw(16) << std::this_thread::get_id() << ": on_next subs,    value = " << x << std::endl;
            });

        // Sleep(1000);
        subject.get_subscriber().on_next(100);
        Sleep(1000);
        subject.get_subscriber().on_next(200);
        Sleep(1000);
        subject.get_subscriber().on_next(300);
        Sleep(1000);

```

**Comment by kirkshoop** [comment]
Yes. This is expected behavior. 

if you want a subject that will buffer values for late subscribers you use `replay`.

however, in this case, I would expect to use `observe_on` not `subscribe_on`.

`subscribe_on` will call the `subscribe` on the `subject` (which just pushes the observer in a queue) from a new thread, but all the `on_next` calls will be from the main thread.

**Comment by nikobarli** [comment]
Thanks for the clarification. It was counter intuitive at first since I have already called subscribe before calling on_next of the subject, and still the first item was missing. 

Do you know if Rx.NET has the same behavior ? I never encounter it, but it may be just because of the timing. 

# Yes, I usually use observe_on and very rarely use subscribe_on.

**Comment by kirkshoop** [comment]
Yes, I suspect that the .Net would also race. if the SubscribeOn is using the thread pool it might subscribe quickly enough to catch the first OnNext
