### ISSUE TITLE
 fatal error:        'catch.hpp' file not found

### ISSUE THREAD

**Issue by zhou0** [Reactive-Extensions/RxCpp#407]
[  0%] Building CXX object build/test/CMakeFiles/rxcpp_test_window_toggle.dir/operators/window_toggle.cpp.o
In file included from /usr/home/lzhou/github.com/Reactive-Extensions/RxCpp/archive/RxCpp-4.0.0/Rx/v2/test/operators/window_toggle.cpp:1:
/usr/home/lzhou/github.com/Reactive-Extensions/RxCpp/archive/RxCpp-4.0.0/Rx/v2/test/operators/../test.h:22:10: fatal error: 
      'catch.hpp' file not found
#include "catch.hpp"
         ^~~~~~~~~~~
1 error generated.
*** Error code 1

Stop.
make[2]: stopped in /usr/home/lzhou/github.com/Reactive-Extensions/RxCpp/archive/RxCpp-4.0.0/build
*** Error code 1

Stop.
make[1]: stopped in /usr/home/lzhou/github.com/Reactive-Extensions/RxCpp/archive/RxCpp-4.0.0/build
*** Error code 1

Stop.
make: stopped in /usr/home/lzhou/github.com/Reactive-Extensions/RxCpp/archive/RxCpp-4.0.0/build

**Comment by kirkshoop** [comment]
Hi! Catch is a git submodule, the git clone must be recursive to include the submodule.
