### ISSUE TITLE
Lock-free scheduling?

### ISSUE THREAD

**Issue by martinfinke** [Reactive-Extensions/RxCpp#408]
Would it be possible to implement lock-free scheduling as follows? 

I have two threads: The "main" thread for the GUI, and a high-priority background thread. The background thread has a strict low-latency requirement: It must never have to wait for the main thread.

I have a Subject `s`, and observe it on the main thread: `s.get_observable().observe_on(<main thread worker>).map(…)`.

I call `s.on_next()` on the background thread. From `rx-observe_on.hpp` it looks like this locks a mutex which is also locked by the main thread, right? If so, would it be possible to do scheduling such that `on_next` (and `on_error`, `on_completed`) don't need locking? I'm thinking of using lock-free queues, but from looking at the RxCpp source, I'm not sure how this could be done.

Any input or ideas are greatly appreciated. Thanks! :)

**Comment by kirkshoop** [comment]
Perhaps you have already given this a try. Observe_on seems to be solving a different problem.

If you want a lock free solution the best way is to wrap an existing lock-free queue or threadpool or task library in an new rxcpp scheduler and then pass that scheduler to the `delay()` operator with a delay of zero ;)

Delay will just call `sched.schedule(sched.now() + 0, [v, out](){out.on_next(v);});` with you providing both now() and schedule() you can fully control the behavior.

**Comment by martinfinke** [comment]
Thanks so much! I'll give that a try.
