### ISSUE TITLE
Support for And/Then/When (Pattern/Plan)?

### ISSUE THREAD

**Issue by djleach-belcan** [Reactive-Extensions/RxCpp#426]
Is there support for the And/Then/When operators described [here](http://reactivex.io/documentation/operators/and-then-when.html)? If not, is equivalent functionality possible? Thanks.

**Comment by kirkshoop** [comment]
Looking at the docs, I think this is covered by the `zip` operator in rxcpp. `zip` uses variadic templates to combine an arbitrary number of streams without needing `and`. the result is an observable, so no need for `then` or `when`

is there a use case that is not supported by `zip`?

**Comment by djleach-belcan** [comment]
Ah, I see that now, thanks. No use case I can think of yet that isn't supported; I wanted to see what was available first before trying to solve my problem and noticed those were missing.
