### ISSUE TITLE
Consider renaming of root namespace (rxcpp)  

### ISSUE THREAD

**Issue by furuholm** [Reactive-Extensions/RxCpp#5]
The cpp in the rxcpp namespace seems superfluous. I therefore suggest that a switch of the base namespace should be considered.

Rx.Net uses the namespace reactive and RxJava uses the namespace rx. So the two natural suggestions would be "reactive" and "rx". 

I would prefer "rx" since it reads much better (in the test code @kirkshoop has aliased the rxcpp namespace to rx). I know however that @kirkshoop considers it too short and that it therefore could clash with the name of classes or a namespaces in existing codebases. However, I would argue that an existing codebase could just as well have a class called reactive as a class called rx (don't have any data whatsoever to back that up though :). It seems less likely that a user have class called rxcpp, so I guess that this comes down to a tradeoff between "grade of uniqueness" vs. "nice and readable".

**Comment by daixtrose** [comment]
This issue is closed without a comment why it was closed. Please document if there is a code change or not amd the reasons behind that.

**Comment by furuholm** [comment]
I made this proposal over a year ago and since it has not been adopted I figured that I might as well close the issue. 

Sorry for not leaving a comment and thanks for pointing that out!
