### ISSUE TITLE
concat_map_factory initialiser list passes arguments in the wrong order

### ISSUE THREAD

**Issue by BenPope** [Reactive-Extensions/RxCpp#58]
Collector and Result are swapped, which prevents usage of pipe and stream.

**Comment by kirkshoop** [comment]
Would you provide a sample of the usage you want?

**Comment by BenPope** [comment]
The code is:
    concat_map_factory(collection_selector_type s, result_selector_type rs, coordination_type sf)
        : selectorCollection(std::move(rs))
        , selectorResult(std::move(s))
        , coordination(std::move(sf))
    {
    }
}
It should be
    concat_map_factory(collection_selector_type s, result_selector_type rs, coordination_type sf)
        : selectorCollection(std::move(s))
        , selectorResult(std::move(rs))
        , coordination(std::move(sf))
    {
    }

**Comment by kirkshoop** [comment]
Ah, that helps!
so usage would look like 
```c++
rx::observable<int> xs;
rx::observable<std::string> ys;
xs >> rxo::concat_map(
  [&](int){return ys;},
  [](int, std::string s){return s;}, 
  rx::identity_current_thread());
```

I have a fix for concat_map and flat_map. I will create a PR soon.

Thanks!

**Comment by BenPope** [comment]
Thank you!
